### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by nathannli** [shelby-cobra/rtl8822bu-dkms#3]
Hey Shelby,

Just wondering how to use this? I found your code from this link:
https://github.com/brandon-bailey/rtl8822bu/issues/7

Currently on kernel version is 4.13

**Comment by shelby-cobra** [comment]
hey nathannli,
its for Archlinux only. i added installation instructions to readme.md. 
I only can try it on kernel 4.12 and 4.9. Please give feedback for 4.13

**Comment by theredbaron1834** [comment]
Compiles and runs fine on "4.13.3-1-ARCH". The only one I can find that does too :).

**Comment by shelby-cobra** [comment]
@theredbaron1834  thanks, i think i'll submit it as package in AUR the next days
